---
downloads: ~/.ansible-downloads/

configure_dotfiles: false
configure_terminal: true
configure_osx: true

# Set to 'true' to configure the Dock via dockutil.
configure_dock: true
dockitems_remove:
  - Launchpad
  - TV
  - Podcasts
  - 'App Store'
  - Music
  - Reminders
  - FaceTime
  - Mail
  - Safari
  - Messages
  - Maps
  - Contacts
  - Notes
dockitems_persist:
  - name: "Sublime Text"
    path: "/Applications/Sublime Text.app/"
    pos: 5
  - name: "Visual Studio Code"
    path: "/Applications/Visual Studio Code.app/"
    pos: 2
  - name: "Slack"
    path: "/Applications/Slack.app/"
    pos: 3
  - name: "TeamViewer"
    path: "/Applications/TeamViewer.app/"
    pos: 4
  - name: "Terminal"
    path: "/Applications/Utilities/Terminal.app/"
    pos: 6
  - name: "Discord"
    path: "/Applications/Discord.app/"
    pos: 7
  - name: "Authy Desktop"
    path: "/Applications/Authy Desktop.app/"
    pos: 8
  - name: "Whatsapp"
    path: "/Applications/Whatsapp.app/"
    pos: 9
  - name: "Microsoft Edge"
    path: "/Applications/Microsoft Edge.app/"
    pos: 10
  - name: "Google Chrome"
    path: "/Applications/Google Chrome.app/"
    pos: 11
  - name: "Workspaces"
    path: "/Applications/Workspaces.app/"
    pos: 12

configure_sudoers: false
sudoers_custom_config: ''
# Example:
# sudoers_custom_config: |
#   # Allow users in admin group to use sudo with no password.
#   %admin ALL=(ALL) NOPASSWD: ALL

dotfiles_repo: https://github.com/geerlingguy/dotfiles.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/Development/GitHub/dotfiles
dotfiles_files:
  - .zshrc
  - .gitignore
  - .inputrc
  - .osx
  - .vimrc

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - "1password"
  - "amazon-workspaces"
  - adobe-creative-cloud
  - autoconf
  - bash-completion
  - doxygen
  - dockutil
  - gettext
  - gifsicle
  - git
  - github/gh/gh
  - go
  - gpg
  - httpie
  - iperf
  - libevent
  - sqlite
  - mcrypt
  - nmap
  - node
  - nvm
  - php
  - python
  - ssh-copy-id
  - cowsay
  - readline
  - openssl
  - pv
  - "ringcentral"
  - terraform
  - wget
  - wrk
  - zsh-history-substring-search
  - htop
  - watch
  - minikube
  - "synology-note-station-client"

homebrew_taps:
  - homebrew/core
  - homebrew/cask

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - authy
  - caffeine
  - chromedriver
  - cloudmounter
  - daisydisk
  - docker
  - dropbox
  - firefox
  - forklift
  - google-cloud-sdk
  - google-chrome
  - handbrake
  # - istat-menus
  - licecap
  - microsoft-edge
  - microsoft-office
  - Microsoft-teams
  - mountain-duck
  - sequel-ace
  - slack
  - sublime-text
  - transmit
  - vagrant
  - discord
  - authy
  - loom
  - google-drive
  - visual-studio-code
  - vlc
  - opera
  - skype
  - zoom
  - whatsapp
  - synology-note-station-client

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: []
mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
# - name: drush
#   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A
gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A
npm_packages: []
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
pip_packages: []
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

# Set to 'true' to configure Sublime Text.
configure_sublime: false
sublime_base_path: '~/Library/Application Support/Sublime Text'
sublime_config_path: "Packages/User"
sublime_package_control:
  - "DocBlockr"
  - "Dockerfile Syntax Highlighting"
  - "FileDiffs"
  - "GitHub Flavored Markdown Preview"
  - "Jinja2"
  - "Package Control"
  - "PHP-Twig"
  - "Pretty JSON"
  - "SublimeLinter"
  - "SublimeLinter-contrib-yamllint"
  - "TrailingSpaces"
  - "WordCount"

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
